name: run_and_post_to_mastodon

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

env:
  MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
jobs:
  run_and_post:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      # Run the scripts
      - name: run scripts
        run: Rscript R/0_MASTER.R

